import { CaseDto } from './../app/domain/case.dto';
const MuifaCase: CaseDto = {
  _id: '673ea2a5de8c51b322de4b08',
  name: '2022梅花',
  values: {
    台风命名: {
      key: '台风命名',
      type: '通用',
      value: '2022梅花',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风年度: {
      key: '台风年度',
      type: '通用',
      value: '2022',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风类型: {
      key: '台风类型',
      type: '通用',
      value: '强台风',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风编号: {
      key: '台风编号',
      type: '通用',
      value: '202212',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风路径图: {
      key: '台风路径图',
      type: '通用',
      value: '2022梅花',
      editorType: '图片配置',
      editorOptions: [],
    },
    英文名称: {
      key: '英文名称',
      type: '通用',
      value: 'Muifa',
      editorType: '文本配置',
      editorOptions: [],
    },
    发生时间: {
      key: '发生时间',
      type: '通用',
      value: '2022年9月6日',
      editorType: '文本配置',
      editorOptions: [],
    },
    影响线路: {
      key: '影响线路',
      type: '通用',
      value: '全线',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风走向: {
      key: '台风走向',
      type: '通用',
      value: '东南',
      editorType: '文本配置',
      editorOptions: ['东', '南', '西', '北', '东南', '东北', '西南', '西北'],
    },
    台风生成时间: {
      key: '台风生成时间',
      type: '时间节点',
      value: '2022/9/6  14:00:00，9月6日台风梅花生成',
      editorType: '文本配置',
      editorOptions: [],
    },
    预警发布时间: {
      key: '预警发布时间',
      type: '时间节点',
      value: '2022/9/13  19:00:00，9月13日上海发布蓝色台风预警',
      editorType: '文本配置',
      editorOptions: [],
    },
    最高预警时间: {
      key: '最高预警时间',
      type: '时间节点',
      value: '2022/9/14  16:00:00，9月14日预警升级为橙色台风预警',
      editorType: '文本配置',
      editorOptions: [],
    },
    预警解除时间: {
      key: '预警解除时间',
      type: '时间节点',
      value: '2022/9/15  9:35:00，9月15日逐级解除台风预警',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风消散时间: {
      key: '台风消散时间',
      type: '时间节点',
      value: '2022/9/17  5:00:00，9月17日台风梅花消散',
      editorType: '文本配置',
      editorOptions: [],
    },
    影响上海时长: {
      key: '影响上海时长',
      type: '事件影响',
      value: '70小时',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风最大风力: {
      key: '台风最大风力',
      type: '事件影响',
      value: '48m/s',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风最大预警等级: {
      key: '台风最大预警等级',
      type: '事件影响',
      value: '橙色预警',
      editorType: '文本配置',
      editorOptions: [],
    },
    共计发布预警指令: {
      key: '共计发布预警指令',
      type: '运行措施',
      value: '12条',
      editorType: '文本配置',
      editorOptions: [],
    },
    停运线路数: {
      key: '停运线路数',
      type: '运行措施',
      value: '16条',
      editorType: '文本配置',
      editorOptions: [],
    },
    影响事件: {
      key: '影响事件',
      type: '运行措施',
      value: '17件',
      editorType: '文本配置',
      editorOptions: [],
    },
    施工调整: {
      key: '施工调整',
      type: '运行措施',
      value: '427起',
      editorType: '文本配置',
      editorOptions: [],
    },
    热线接听总量: {
      key: '热线接听总量',
      type: '舆情信息',
      value: '2487起',
      editorType: '文本配置',
      editorOptions: [],
    },
    人工接听总量: {
      key: '人工接听总量',
      type: '舆情信息',
      value: '1450起',
      editorType: '文本配置',
      editorOptions: [],
    },
    台风相关咨询建议: {
      key: '台风相关咨询建议',
      type: '舆情信息',
      value: '1127起',
      editorType: '文本配置',
      editorOptions: [],
    },
    舆情概况: {
      key: '舆情概况',
      type: '舆情信息',
      value: '总体平稳',
      editorType: '文本配置',
      editorOptions: [],
    },
    特殊展示归类: {
      key: '特殊展示归类',
      type: '通用',
      value: '范围较大',
      editorType: '文本配置',
      editorOptions: [],
    },
    及时性: {
      key: '及时性',
      type: '运行措施',
      value: '5',
      editorType: '下拉框配置',
      editorOptions: ['1', '2', '3', '4', '5'],
    },
    合理性: {
      key: '合理性',
      type: '运行措施',
      value: '5',
      editorType: '下拉框配置',
      editorOptions: ['1', '2', '3', '4', '5'],
    },
    总体评价: {
      key: '总体评价',
      type: '运行措施',
      value: '优',
      editorType: '下拉框配置',
      editorOptions: ['优', '良', '差'],
    },
    评价文本: {
      key: '评价文本',
      type: '运行措施',
      value: '测试文本，巴拉巴拉哔哩哔哩巴拉巴拉巴拉巴拉吧',
      editorType: '文本配置',
      editorOptions: [],
    },
    影响日期: {
      key: '影响日期',
      type: '对比专用字段',
      value: '例：周一、周二……周日',
      editorOptions: [],
    },
    '"六停”、“三停”情况': {
      key: '"六停”、“三停”情况',
      type: '对比专用字段',
      value: '2023年-该规章启用',
      editorOptions: [],
    },
    发布指令: {
      key: '发布指令',
      type: '对比专用字段',
      value:
        '先后下发了《切实做好2022年第12号台风“梅花”防御工作》、《强化12、13日本市雷电、暴雨期间轨道交通防范工作》、《9月14日上海地铁部分线路暂停运营》、《做好9月15日停运线路、区段恢复正常运营准备工作》、《9月15日上海地铁1、2、3、4、5、6、7、8、9、10、11、16、17、浦江线及磁浮线恢复正常运营》等12条工作指令',
      editorOptions: [],
    },
    预警信息: {
      key: '预警信息',
      type: '对比专用字段',
      value:
        '期间转发市气象及防汛部门预警11次，其中气象灾害7次（台风：蓝色2次、黄色和橙色各1次；暴雨：黄色和橙色各1次；黄浦江高潮位：蓝色1次。）、防汛防台4次（Ⅳ级响应行动2次、Ⅲ与Ⅱ级响应行动各1次）',
      editorOptions: [],
    },
    停运形式: {
      key: '停运形式',
      type: '对比专用字段',
      value: '预防性停运、事前停运、事中停运',
      editorOptions: [],
    },
    突发事件: {
      key: '突发事件',
      type: '对比专用字段',
      value: '17件',
      editorOptions: [],
    },
    重要影响事件: {
      key: '重要影响事件',
      type: '对比专用字段',
      value: '11号线1173#车故障救援',
      editorOptions: [],
    },
    官方微博: {
      key: '官方微博',
      type: '对比专用字段',
      value: '10条',
      editorOptions: [],
    },
    官方微信: {
      key: '官方微信',
      type: '对比专用字段',
      value: '1条',
      editorOptions: [],
    },
    '直播、采访': {
      key: '直播、采访',
      type: '对比专用字段',
      value: '2次',
      editorOptions: [],
    },
    处置评价: {
      key: '处置评价',
      type: '对比专用字段',
      value: '1、14日9时起集团启用“小时报”制度\n2、启用“一洞一长”机制',
      editorOptions: [],
    },
  },
  status: 0,
  createdAt: '2024-11-21T03:01:57.209Z',
  updatedAt: '2025-03-05T08:29:53.716Z',
  __v: 0,
};

export const DUMMY_TYPHOON_CASE = {
  MuifaCase,
};
