export const intervalData = {
  lines: {
    five: [
      {
        id: 'line1',
        line1_car: 15,
        line1_time: 5,
      },
      {
        id: 'line2',
        line2_car: 24,
        line2_time: 5,
      },
      {
        id: 'line4',
        line4_car: 17,
        line4_time: 5,
      },
      {
        id: 'line6',
        line6_car: 17,
        line6_time: 5,
      },
      {
        id: 'line7',
        line7_car: 30,
        line7_time: 5,
      },
      {
        id: 'line8',
        line8_car: 26,
        line8_time: 5,
      },
      {
        id: 'line9',
        line9_car_left: 6,
        line9_car_right: 29,
        line9_time_left: 5,
        line9_time_right: 5,
      },
      {
        id: 'line10',
        line8_car: 24,
        line10_time: 5,
      },
      {
        id: 'line11',
        line11_car: 22,
        line11_time: 5,
      },
      {
        id: 'line12',
        line12_car: 34,
        line12_time: 5,
      },
      {
        id: 'line13',
        line13_car: 33,
        line13_time: 5,
      },
      {
        id: 'line14',
        line14_car: 31,
        line14_time: 5,
      },
      {
        id: 'line15',
        line15_car: 31,
        line15_time: 5,
      },
      {
        id: 'line18',
        line18_car: 28,
        line18_time: 5,
      },
      {
        id: 'line20',
        line20_car: 5,
        line20_time: 5,
      },
    ],
    eightyPercent: [
      {
        id: 'line1',
        line1_car: 8,
        line1_time: 8,
      },
      {
        id: 'line2',
        line2_car: 15,
        line2_time: 8,
      },
      {
        id: 'line4',
        line4_car: 11,
        line4_time: 8,
      },
      {
        id: 'line6',
        line6_car: 11,
        line6_time: 8,
      },
      {
        id: 'line7',
        line7_car: 19,
        line7_time: 8,
      },
      {
        id: 'line8',
        line8_car: 17,
        line8_time: 8,
      },
      {
        id: 'line9',
        line9_car_left: 4,
        line9_car_right: 19,
        line9_time_left: 8,
        line9_time_right: 8,
      },
      {
        id: 'line10',
        line8_car: 16,
        line10_time: 8,
      },
      {
        id: 'line11',
        line11_car: 14,
        line11_time: 8,
      },
      {
        id: 'line12',
        line12_car: 22,
        line12_time: 8,
      },
      {
        id: 'line13',
        line13_car: 21,
        line13_time: 8,
      },
      {
        id: 'line14',
        line14_car: 19,
        line14_time: 8,
      },
      {
        id: 'line15',
        line15_car: 20,
        line15_time: 8,
      },
      {
        id: 'line18',
        line18_car: 17,
        line18_time: 8,
      },
      {
        id: 'line20',
        line20_car: 0,
        line20_time: 8,
      },
    ],
    ten: [
      {
        id: 'line1',
        line1_car: 7,
        line1_time: 10,
      },
      {
        id: 'line2',
        line2_car: 12,
        line2_time: 10,
      },
      {
        id: 'line4',
        line4_car: 9,
        line4_time: 10,
      },
      {
        id: 'line6',
        line6_car: 9,
        line6_time: 10,
      },
      {
        id: 'line7',
        line7_car: 16,
        line7_time: 10,
      },
      {
        id: 'line8',
        line8_car: 14,
        line8_time: 10,
      },
      {
        id: 'line9',
        line9_car_left: 4,
        line9_car_right: 15,
        line9_time_left: 10,
        line9_time_right: 10,
      },
      {
        id: 'line10',
        line8_car: 13,
        line10_time: 10,
      },
      {
        id: 'line11',
        line11_car: 11,
        line11_time: 10,
      },
      {
        id: 'line12',
        line12_car: 17,
        line12_time: 10,
      },
      {
        id: 'line13',
        line13_car: 17,
        line13_time: 10,
      },
      {
        id: 'line14',
        line14_car: 16,
        line14_time: 10,
      },
      {
        id: 'line15',
        line15_car: 16,
        line15_time: 10,
      },
      {
        id: 'line18',
        line18_car: 14,
        line18_time: 10,
      },
      {
        id: 'line20',
        line20_car: 2,
        line20_time: 10,
      },
    ],
  },
};
export const requirement_content = {
  blueAlert: {
    onDutyEscort:
      '加强一线关键岗位值班值守;密切监视天气动态变化与汛情灾情,及时落实应对措施;C0CC及时发布应对灾害天气的防御工作要求或工作指令。',
    patrolInspection:
      '加强重点部位、薄弱环节巡视检查，频次不应低于每2小时一次;站外独立变电站等其他部位，应至少增加一次巡检;实施"一洞一长"机制，安排专人落实"人机结合"巡检，频次不应低于每2小时一次;视情调整或取消非必要施工计划，增设防汛防台保障临时巡检施工;做好防洪排涝设施设备的性能检查与加固紧固，加强重点部位渗漏水、积水、淹水倒灌、异物侵限等情况的排摸处置;司机(多职能列控)应加强安全瞭望，如遇异常情况要立即采取安全措施并上报;如遇异常情况，应立即安排专人至现场巡查确认或登车保驾，并及时采取防排水、异物清除、设备维修等措施;如接到高潮位、洪水等预警信息，沿江、河、湖场所应密切监视汛情险情。',
    otherRequirements:
      '车站应针对出入口、通道、站台、楼/扶梯等重点部位做好防滑防护措施，加强乘客出行安全宣传与提示;落实作业安全防护措施，保障人员安全、作业安全。',
  },
  yellowAlert: {
    onDutyEscort:
      '相关直属单位的职能部门、线路管理部、维护部等负责人加强值班值守，对一线作业进行监督指导;加强灾害天气风险及影响研判;抢险队伍进入应急值班状态，做好抢险物资随时调运的准备。',
    patrolInspection:
      '进一步提升重点部位、薄弱环节巡视检查频次，频次不应低于每1小时一次;其他部位应视情增加巡视频次;进一步加强"一洞一长"巡视检查，频次不应低于每1小时一次;加强各项夜间检修工作，重点做好防汛防台设施、各类附属设施、区间垃圾和易积水区段的检查、维护、清理工作;司机(多职能列控)应进一步加强对沿线洞口区域、异物侵限、设施设备故障/松脱、区间积水等情况的安全瞭望。',
    otherRequirements:
      '加强车站客流秩序管控、重点部位布岗，防止客流对冲风险;根据需要及时采取关闭出入口降级运行、限速运行等调整措施。',
  },
  redAlert: {
    onDutyEscort:
      '相关直属单位主要领导组织指挥全力投入抢险救援工作;全面加强汛情监控、影响研判、信息互通、联动协作，全面投入应急抢险工作;抢险队伍进入应急抢险状态，各单位积极为防汛防台工作提供全力保障。',
    patrolInspection:
      '全面落实不间断巡视检查与措施落实，做到早发现、早处置，确保运营安全有序可控。',
    otherRequirements:
      '进一步严密关注轨道交通运营安全，全力做好行车组织调整、客运组织、抢险抢修工作，保障人员安全，将影响和损失降至最低。',
  },
  orangeAlert: {
    onDutyEscort:
      '相关直属单位进一步加强领导干部值班，分管领导及时组织落实各项防御应对措施与抢险处置工作;抢险队伍进入应急处置状态，做好抢险力量即时响应的准备。',
    patrolInspection:
      '针对重点部位、薄弱环节实施不间断巡视检查，站外独立变电站、运营线路未开通车站、建设运营接口部位等场所应安排人员24小时值守;进一步加强"一洞一长"巡视检查，洞口管理责任人应安排专人进行24小时现场值守巡视;3.司机(多职能列控)应在列车头端侧值守瞭望。',
    otherRequirements:
      '根据需要进一步采取关站、停运、正线留车过夜等措施:及时联合属地力量或向上级申请支援，做好滞留乘客的疏导转运;加强与市、区防汛指挥机构的联系，必要时申请外部力量支援。',
  },
};
// 出入口数据
export const grading_table = [
  {
    line: '1号线',
    stationName: '新闻路',
    entranceExit: '6号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '中山北路',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '延长路',
    entranceExit: '3号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '上海马戏城',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '上海马戏城',
    entranceExit: '3号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '人民广场',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '徐家汇',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '徐家汇',
    entranceExit: '13号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '徐家汇',
    entranceExit: '14号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '1号线',
    stationName: '陕西南路站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '陕西南路站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '上海南站站',
    entranceExit: '6号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '1号线',
    stationName: '黄陂南路',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '2号线',
    stationName: '南京西路',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '2号线',
    stationName: '静安寺',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '2号线',
    stationName: '广兰路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '2号线',
    stationName: '金科路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '2号线',
    stationName: '创新中路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '2号线',
    stationName: '创新中路',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R4',
  },
  {
    line: '2号线',
    stationName: '创新中路',
    entranceExit: '4号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '3号线',
    stationName: '上海火车站',
    entranceExit: '6号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '3号线',
    stationName: '上海火车站',
    entranceExit: '7号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '3号线',
    stationName: '上海火车站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '3号线',
    stationName: '上海火车站',
    entranceExit: '10号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '3号线',
    stationName: '上海火车站',
    entranceExit: '7号口',
    type: '无障碍电梯1',
    riskLevel: 'R2',
  },
  {
    line: '3号线',
    stationName: '上海南站站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '3号线',
    stationName: '上海南站站',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R2',
  },
  {
    line: '5号线',
    stationName: '环城东路',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '5号线',
    stationName: '环城东路',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '5号线',
    stationName: '金海湖',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '5号线',
    stationName: '奉贤新城',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '5号线',
    stationName: '奉贤新城',
    entranceExit: '3号口',
    type: '消防通道2',
    riskLevel: 'R3',
  },
  {
    line: '5号线',
    stationName: '奉贤新城',
    entranceExit: '3号口',
    type: '消防通道3',
    riskLevel: 'R3',
  },
  {
    line: '7号线',
    stationName: '潘广路',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '7号线',
    stationName: '杨高南路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '老西门站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '老西门站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '老西门站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '老西门站',
    entranceExit: '地面消防救援通道',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '四平路站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '8号线',
    stationName: '四平路站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '四平路站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '8号线',
    stationName: '四平路站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '8号线',
    stationName: '四平路站',
    entranceExit: '2号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '上海松江站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '中春路站',
    entranceExit: '5号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '中春路站',
    entranceExit: '6号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '七宝站',
    entranceExit: '1号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '桂林路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '桂林路',
    entranceExit: '1号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '徐家汇',
    entranceExit: '15号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '徐家汇',
    entranceExit: '15号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '嘉善路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '嘉善路',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '嘉善路',
    entranceExit: '4号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '打浦桥',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '马当路',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '杨高中路',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '9号线',
    stationName: '杨高中路',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R4',
  },
  {
    line: '9号线',
    stationName: '芳甸路',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '9号线',
    stationName: '芳甸路',
    entranceExit: '1号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '芳甸路',
    entranceExit: '1号口',
    type: '消防通道1',
    riskLevel: 'R4',
  },
  {
    line: '9号线',
    stationName: '顾唐路',
    entranceExit: '2号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '7号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '10号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '11号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '7号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '8号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '9号线',
    stationName: '宜山路站',
    entranceExit: '9号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '虹桥1号航站楼站',
    entranceExit: '地面消防救援通道',
    type: '消防通道1',
    riskLevel: 'R4',
  },
  {
    line: '10号线',
    stationName: '上海动物园站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '10号线',
    stationName: '伊犁路站',
    entranceExit: '1号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '豫园站',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '一大会址·新天地站',
    entranceExit: '1号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '四川北路站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '四川北路站',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '同济大学站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '同济大学站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '10号线',
    stationName: '三门路站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '10号线',
    stationName: '三门路站',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R4',
  },
  {
    line: '10号线',
    stationName: '陕西南路站',
    entranceExit: '7号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '11号线',
    stationName: '徐家汇',
    entranceExit: '18号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '徐家汇',
    entranceExit: '18号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '康恒路',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '康恒路',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '康恒路',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '康恒路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '康恒路',
    entranceExit: '1号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '浦三路',
    entranceExit: '地面无障碍电梯',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '三林',
    entranceExit: '地面无障碍电梯',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '龙耀路',
    entranceExit: '地面无障碍电梯',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '龙华',
    entranceExit: '地面无障碍电梯',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '上海游泳馆',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '上海游泳馆',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '上海游泳馆',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '11号线',
    stationName: '上海游泳馆',
    entranceExit: '地面无障碍电梯',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '天津路站',
    entranceExit: '3号口',
    type: '消防通道1',
    riskLevel: 'R2',
  },
  {
    line: '12号线',
    stationName: '大木桥路站',
    entranceExit: '6号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '虹梅路',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '虹梅路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '虹梅路',
    entranceExit: '5号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '虹梅路',
    entranceExit: '5号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '国际客运中心',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '12号线',
    stationName: '国际客运中心',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '马当路',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '马当路',
    entranceExit: '5号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '一大会址·新天地站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '一大会址·新天地站',
    entranceExit: '4号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '长寿路站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '长寿路站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '13号线',
    stationName: '长寿路站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '长寿路站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '13号线',
    stationName: '长寿路站',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '豫园站',
    entranceExit: '5号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '豫园站',
    entranceExit: '1号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '静安寺',
    entranceExit: '11号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '静安寺',
    entranceExit: '12号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '静安寺',
    entranceExit: '13A号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '静安寺',
    entranceExit: '13B号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '静安寺',
    entranceExit: '14号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '静安寺',
    entranceExit: '15号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '14号线',
    stationName: '浦东大道',
    entranceExit: '7A号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '浦东大道',
    entranceExit: '7B号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '14号线',
    stationName: '浦东大道',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '14号线',
    stationName: '昌邑路',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '真如',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '14号线',
    stationName: '中宁路',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '大世界',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '大世界',
    entranceExit: '5号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '一大会址·黄陂南路',
    entranceExit: '7号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '武宁路',
    entranceExit: '4号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '14号线',
    stationName: '曹杨路',
    entranceExit: '10号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '15号线',
    stationName: '南大路站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '15号线',
    stationName: '娄山关路站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '华东理工大学站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '紫竹高新区站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '15号线',
    stationName: '紫竹高新区站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '紫竹高新区站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '紫竹高新区站',
    entranceExit: '5号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '紫竹高新区站',
    entranceExit: '4号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '上海南站站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '上海南站站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '15号线',
    stationName: '上海南站站',
    entranceExit: '9号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '17号线',
    stationName: '国家会展中心',
    entranceExit: '16号口',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '17号线',
    stationName: '西岑',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '17号线',
    stationName: '西岑',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '18号线',
    stationName: '杨高中路站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '18号线',
    stationName: '杨高中路站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '18号线',
    stationName: '杨高中路站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R4',
  },
  {
    line: '18号线',
    stationName: '丹阳路站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '虹桥2号航站楼站',
    entranceExit: '消防救援通道',
    type: '消防通道1',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '中春路站',
    entranceExit: '8号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '中春路站',
    entranceExit: '8号口',
    type: '无障碍电梯1',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '中春路站',
    entranceExit: '9A号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '中春路站',
    entranceExit: '9B号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '景洪路站',
    entranceExit: '5号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '景洪路站',
    entranceExit: '6号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '景洪路站',
    entranceExit: '6号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '三林南',
    entranceExit: '1、2号口中间',
    type: '无障碍电梯1',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '三林南',
    entranceExit: '1、2号口中间',
    type: '无障碍电梯2',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '康桥东站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '康桥东站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '康桥东站',
    entranceExit: '2号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '康桥东站',
    entranceExit: '3号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '康桥东站',
    entranceExit: '3号口',
    type: '无障碍电梯2',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '康桥东站',
    entranceExit: '4号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '上海国际旅游度假区站',
    entranceExit: '1号口',
    type: '出入口',
    riskLevel: 'R2',
  },
  {
    line: '市域机场线',
    stationName: '上海国际旅游度假区站',
    entranceExit: '1号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '上海国际旅游度假区站',
    entranceExit: '2号口',
    type: '出入口',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '上海国际旅游度假区站',
    entranceExit: '3号口',
    type: '无障碍电梯2',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '浦东1号2号航站楼站',
    entranceExit: '1号口',
    type: '无障碍电梯1',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '浦东1号2号航站楼站',
    entranceExit: '2号口',
    type: '无障碍电梯2',
    riskLevel: 'R3',
  },
  {
    line: '市域机场线',
    stationName: '浦东1号2号航站楼站',
    entranceExit: '3号口',
    type: '无障碍电梯2',
    riskLevel: 'R3',
  },
];
// 总表数据
export const totalTableData = [
  {
    tropical_storm_name: '2018年安比',
    landing_site: '上海市崇明岛沿海',
    max_wind_power: '7-8级,小洋山10级',
    main_impact_period: '2018年7月22日',
    main_operation_adjustment_measures:
      '7月22日10:05起,2号线东延伸凌空路至浦东国际机场区段、6号线博兴路至港城路区段、16号线全线列车限速45km/h运行;11:45起,6号线部分区段(港城路至巨峰路)暂停运营;12:00起,浦江线全线暂停运营。17:30 6号线恢复运营,18:00浦江线全线恢复运营。',
  },
  {
    tropical_storm_name: '2018年云雀',
    landing_site: '上海金山沿海',
    max_wind_power: '沿江沿海9-10级,滴水湖10级',
    main_impact_period: '2018年8月2日—3日',
    main_operation_adjustment_measures: '',
  },
  {
    tropical_storm_name: '2018年温比亚',
    landing_site: '上海浦东新区南部沿海',
    max_wind_power: '沿江沿海10-11级',
    main_impact_period: '2018年8月16日—17日',
    main_operation_adjustment_measures: '',
  },
  {
    tropical_storm_name: '2019年利奇马',
    landing_site: '浙江温岭城南镇',
    max_wind_power:
      '市区最大风力出现在杨浦区为9级,长江口区和沿江沿海地区最大阵风11级,洋山港区及附近沿岸海域最大阵风13～15级-11级',
    main_impact_period: '2019年8月9日—11日',
    main_operation_adjustment_measures:
      '8月10日运营开始起16号线、浦江线、磁浮线暂停运营,2号线、5号线、6号线、8号线、17号线地面高架段限速40KM/H运行;9:50起2号线部分区段(广兰路至浦东国际机场)暂停运营;11:00起6号线部分区段(港城路至巨峰路)暂停运营;15:00起8号线部分区段(东方体育中心至沈杜公路)暂停运营;15:30起5号全线、9号线部分区段(松江大学城至九亭)暂停运营。8月11日0:00起全网恢复正常运营。',
  },
  {
    tropical_storm_name: '2020年黑格比',
    landing_site: '浙江乐清沿海登陆',
    max_wind_power:
      '沿江沿海9-本市陆地最大阵风10级,江河湖面和沿江沿海地区最大阵风10级,沿海海面最大阵风11级,滴水湖10级',
    main_impact_period: '2020年8月3日—4日',
    main_operation_adjustment_measures: '',
  },
  {
    tropical_storm_name: '2021年烟花',
    landing_site: '浙江嘉兴平湖市沿海',
    max_wind_power:
      '陆地和沿江沿海地区普遍出现9～12级阵风,最大阵风出现在宝山吴淞街道35.6米/秒,洋山港区和沿海海面最大阵风14级',
    main_impact_period: '2021年7月24日—26日',
    main_operation_adjustment_measures:
      '7月25日运营开始起,全网14条线路(1、2、3、4、5、6、7、8、9、10、11、16、17号线、浦江线)地面、高架区段列车限速60km/h运行;自12:05起,6条线路全线(3、5、16、17号线、浦江线、磁浮线)、9条线路地面、高架区段(1、2、4、6、7、8、9、10、11号线)陆续停运,159座车站暂停运营。自7月26日13:30起,各停运线路开始逐步恢复运营,至当日18:00全网各线路均恢复正常运营。',
  },
  {
    tropical_storm_name: '2021年灿都',
    landing_site: '',
    max_wind_power:
      '本市陆地最大阵风10级,沿江沿海地区最大阵风13级。洋山港区及附近沿岸海域最大阵风12～14级,上海市沿海海面和浙江沿海海面最大阵风13～14级。',
    main_impact_period: '2021年9月13日—14日',
    main_operation_adjustment_measures:
      '9月13日运营开始起,轨道交通陆续实施了4条线路全线停运(5号线、16号线、磁浮线、浦江线)、1条线路缩线运营措施(2号线广兰路(不含)至浦东国际机场暂停运营)。自9月14日11:00分起各线路逐步恢复正常运营。',
  },
  {
    tropical_storm_name: '2022年轩岚诺',
    landing_site: '',
    max_wind_power:
      '内陆最大阵风8～9级,沿江沿海地区9～11级,洋山港区及上海沿岸海域10～11级。',
    main_impact_period: '2022年9月5日—6日',
    main_operation_adjustment_measures: '',
  },
  {
    tropical_storm_name: '2022年梅花',
    landing_site: '上海奉贤',
    max_wind_power:
      '沿江沿海地区宝山吴淞街道14级(42.8米/秒),洋山港区和上海市沿海海面嵊泗马迹山菜园气象观测站最大15级(49.3米/秒)',
    main_impact_period: '2022年9月13日—14日',
    main_operation_adjustment_measures:
      '9月14日受台风显著影响,为确保全网运营安全,自21时起3、5、16、17号线、浦江线、磁浮线全线,1、2、4、6、7、8、9、10、11号线地面、高架区段提前结束运营。9月15日6时起全网恢复正常运营。',
  },
  {
    tropical_storm_name: '2023年杜苏芮',
    landing_site: '福建沿海登陆',
    max_wind_power: '登陆时中心附近最大风力为13-15级(40-48米/秒)',
    main_impact_period: '2023年7月27日—29日',
    main_operation_adjustment_measures:
      '9月14日受台风显著影响,为确保全网运营安全,自21时起3、5、16、17号线、浦江线、磁浮线全线,1、2、4、6、7、8、9、10、11号线地面、高架区段提前结束运营。9月15日6时起全网恢复正常运营。',
  },
  {
    tropical_storm_name: '2024年格美',
    landing_site: '台湾岛中北部沿海、福建省莆田市秀屿区',
    max_wind_power: '登陆时中心附近最大风力为13-15级(40-49米/秒)',
    main_impact_period: '2024年7月27日—28日',
    main_operation_adjustment_measures:
      '9月13日运营开始起,轨道交通陆续实施了4条线路全线停运(5号线、16号线、磁浮线、浦江线)、1条线路缩线运营措施(2号线广兰路(不含)至浦东国际机场暂停运营)。自9月14日11:00分起各线路逐步恢复正常运营。',
  },
  {
    tropical_storm_name: '2024年贝碧嘉',
    landing_site: '登陆上海浦东临港新城登陆',
    max_wind_power: '登陆时中心附近最大风力为13-15级(40-50米/秒)',
    main_impact_period: '2024年9月15日—16日',
    main_operation_adjustment_measures:
      '9月15日21时30分起,采取2号线、5号线、11号线、16号线、浦江线地面、高架区段列车视情限速运行,磁浮线提前结束运营;9月16日运营开始起,上海地铁3、5、16、17号线、浦江线、磁浮线全线停止运营,1、2、4、6、7、8、9、10、11号线地面、高架区段车站均停止运营。14:00起,风力影响减小,停运、缩线线路逐步恢复,至18:20全网线恢复正常。',
  },
  {
    tropical_storm_name: '2024年普拉桑',
    landing_site: '第一次浙江省舟山市岱山县登录、第二上海市奉贤区沿海登陆',
    max_wind_power: '登陆时中心附近最大风力为13-15级(40-51米/秒)',
    main_impact_period: '2024年9月19日—20日',
    main_operation_adjustment_measures: '',
  },
  {
    tropical_storm_name: '2024年康妮',
    landing_site: '台湾省台东县沿海',
    max_wind_power: '登陆时中心附近最大风力为13-15级(40-52米/秒)',
    main_impact_period: '2024年10月31日—11月1日',
    main_operation_adjustment_measures: '',
  },
];
